# Generated by Django 6.0 on 2025-12-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='updated_at',
        ),
    ]
