# Generated by Django 6.0 on 2025-12-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
