# Generated by Django 6.0 on 2026-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productspecifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delivery_info',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
